version: '1'

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    env_file: postgres.env
    ports:
      - "5432:5432"
    networks:
      - serv-network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./../db/src/main/sqldelight/ru.krirll/moscowtour/server/init.sq:/docker-entrypoint-initdb.d/init.sql:ro

  moscowtour:
    container_name: moscowtour
    build:
      context: .
      dockerfile: Dockerfile
    env_file: postgres.env
    ports:
      - 8181:8181
    restart: always
    volumes:
      - ./moscowtour/cache/:/usr/local/app/cache:rw
      - ./moscowtour/tickets/:/usr/local/app/files/tickets:rw
    networks:
      - serv-network
    depends_on:
      - postgres

networks:
  serv-network:
    driver: bridge

volumes:
  pgdata:
